### ISSUE TITLE
Swim Competition To-Do List

### ISSUE THREAD

**Issue by C4L86** [omahacodeschool/web-app__swimming-competition#21]
**Phase 0**
- [x] Fork the repository and open it in Sublime

**Phase 1, Part 1**
- [x] Create database schema with Google sheets
- [x] Submit database schema for approval

**Phase 1, Part 2**
- [x] Define your tables in the de/define_schema.rb
- [x] Create a Model for each table
- [x] Build Controllers and Views for each Model

**Phase 2, Part 1**
- [x] Models, Controllers, and Views in order?
- [x] Naming conventions adhered to?

**Phase 2, Part 2**
- [x] C, of CRUD, complete?
- [x] R complete?
- [x] List all competitors for at least 1 event
- [ ] Create, and submit for approval, 1 more feature (I'm thinking compare new times with world records)

**Phase 2, Part 3**
- [x] Restrict access to Top 3 View until event is complete
- [x] Create, and submit for approval, 1 more "restrict" feature (restrict moving to next page until at least one log is made to any given page, maybe)

**Phase 3**
- [x] All basic CRUD operations on all models

**Phase 4**
- [x] Deleting that works up the hierarchy (e.g.- Delete a team: all swimmers, etc. delete too)
- [x] If admin attempts to delete conference, system checks if teams are in that conference and alerts the admin before deleting

**Phase 5**
- [x] Manual "Event Lock" feature prevents editing an event once all info has been logged

**Phase 6**
- [ ] UX design (yet to be defined)
